### ISSUE TITLE
Nested repeaters unable to hydrate with `node.input()` or `v-model`

### ISSUE THREAD

**Issue by justin-schroeder** [formkit/formkit#458]
### Reproduction

https://formkit.link/44bb8f00a799b49833b55e7e4a1b3623 (`node.input`)

### Reproduction

https://formkit.link/3492c58d3f55196088ce29ba9201dee9 (`v-model`)

### Describe the bug

When we defer the hydration of a repeater with `node.input()` or `v-model` the hydration fails and we are left with an empty state (beta.12).

### Environment

• OS: macOS
• Browser Chrome
• Version >106

**Comment by justin-schroeder** [comment]
Woooooooooooooo 🍻. Finally. Fixed in beta.17

**Comment by nhedger** [comment]
Releases `0.17.0`, `0.17.1` and `0.17.2` are indeed fixed but `0.17.3` seems to have a regression because the issue is again present. I'll try creating a minimal repo to demo asap because I wasn't able to reproduce it on the playground, unfortunately.

**Comment by justin-schroeder** [comment]
You sure? 0.17.3 didnt really make any changes to this system at all.

**Comment by nhedger** [comment]
There may be more to this. I'm not able to reproduce a minimal repo.

In my project, installing any of `0.17.0`, `0.17.1` and `0.17.2`, the repeater renders its items when hydrated with `node.input`, as soon as I install `0.17.3`, it consistently fails by not rendering any of the items, and without error.

I'll dig more.

**Comment by nhedger** [comment]
Ok, so it appears I should have been calling `getNode` within `onMounted` to guarantee that the form input is mounted before trying to hydrate it.

```ts
onMounted(async () => {
    const form = getNode('editForm');
    await form.input(initialData.value);
});
```

What I still don't understand is why it works with the other versions.

**Comment by justin-schroeder** [comment]
Can you provide a reproduction of what you are seeing?
