### ISSUE TITLE
Component highlighting not working for Formkit-beta.15 with Nuxt 3.2.0

### ISSUE THREAD

**Issue by Citingdude** [formkit/formkit#577]
### Reproduction

https://stackblitz.com/edit/nuxt-starter-kabg4x?file=package.json

### Describe the bug

Component highlighting in VS Code does not work with Nuxt 3.2.0 and Formkit-beta.15. When I hover over a component, the component is not recognised (image): 

<img width="409" alt="image" src="https://user-images.githubusercontent.com/80922251/218113615-ef959d02-c4ae-450b-b685-2644fe1ff02c.png">

**Expected results:** When I uninstall formkit it works again (after vscode restart):
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/80922251/218113907-e4e16ff3-edfe-4824-8b2a-e41775de9874.png">

Component highlighting (expected result) works with these package combinations installed:

- Nuxt 3.0.0 + Formkit-beta.15
- Nuxt 3.2.0 + Formkit-Beta.4 (Beta.5+ does not work)

### Environment

• OS: [e.g. iOS]
• Browser [e.g. chrome, safari]
• Version [e.g. 22]

**Comment by jimchampagne** [comment]
I can confirm this bug. I have the exact same behaviour in my own environment. Really would love to get this fixed.

**Comment by andrew-boyd** [comment]
@Citingdude @jimchampagne I believe this is fixed (mostly) on the `@next` tag. See this PR for details: https://github.com/formkit/formkit/pull/581

**Comment by Ragura** [comment]
This bug has not been fixed on @next. Installed package versions are:
```
"@formkit/icons": "1.0.0-beta.16-be1c30f",
"@formkit/nuxt": "1.0.0-beta.16-be1c30f",
"@formkit/themes": "1.0.0-beta.16-be1c30f",
```
There is still no highlighting or intellisense in VSCode. The component does work however.

Full list of installed packages in case it matters:
```
"devDependencies": {
    "@antfu/eslint-config": "latest",
    "@nuxtjs/google-fonts": "3.0.0-1",
    "@nuxtjs/tailwindcss": "^6.4.0",
    "@types/lodash-es": "^4.17.6",
    "eslint": "^8.34.0",
    "eslint-plugin-tailwindcss": "latest",
    "nuxt": "^3.2.0",
    "nuxt-icon": "^0.2.11",
    "prisma": "^4.10.1",
    "typescript": "^4.9.5"
  },
  "dependencies": {
    "@formkit/icons": "1.0.0-beta.16-be1c30f",
    "@formkit/nuxt": "1.0.0-beta.16-be1c30f",
    "@formkit/themes": "1.0.0-beta.16-be1c30f",
    "@nuxt/image-edge": "1.0.0-27919678.2f5b64b",
    "@nuxtjs/i18n": "8.0.0-beta.9",
    "@pinia/nuxt": "^0.4.6",
    "@prisma/client": "^4.10.1",
    "@vueuse/core": "^9.12.0",
    "@vueuse/nuxt": "^9.12.0",
    "lodash-es": "^4.17.21",
    "pinia": "^2.0.30",
    "zod": "^3.20.6"
  },
"pnpm": {
    "overrides": {
      "tailwindcss": "3.2.7",
      "vue": "3.2.47"
    }
  }
```

**Comment by justin-schroeder** [comment]
Just double checked — its working just fine on the @next tag. I see you filed 2 issues just now @Ragura that both would resolve with the latest next tag. sometimes dependencies can get stuck. Try deleting your node_modules directory, maybe your lock file too. Re-install and restart vscode.

**Comment by Ragura** [comment]
Thanks for getting back to me so quickly @justin-schroeder. To make sure it wasn't an issue on my end related to `node_modules`, I've deleted both that folder and the lockfile. The issue still persisted on re-install. To further experiment, I tried `npm` instead of `pnpm` as that is known to cause issues now and then, but same result.
I have created a minimal reproduction which includes only the base Nuxt 3 install, Formkit's packages at `@next` version and the Tailwindcss Nuxt plugin. You can find it here: https://github.com/Ragura/formkit-importing-issue

You are correct that both of my posted issues might be related somehow, but I can't tell what's wrong, if it's something I'm doing, something machine specific or a deeper issue with the packages (I'm not saying it is!). The minimal reproduction is literally just following simple instructions.

If you could clone the reproduction and still don't see the same problems, the formkit highlighting as well as the typescript error when importing genesis, I'll be at a loss 😬

**Comment by justin-schroeder** [comment]
Thank you for the reproduction — that was very helpful. I think I found the culprit. Apparently the `formkit.config.ts` file needs to "touch" the `@formkit/vue` import in some way in order for the typings to appear. The most helpful way to do that would be to import the config definition. For example, your `formkit.config.ts` was:

```ts
import { generateClasses } from '@formkit/themes'
import { genesisIcons } from '@formkit/icons'
import genesis from '@formkit/themes/tailwindcss/genesis'

export default {
  icons: {
    ...genesisIcons,
  },
  config: {
    classes: generateClasses(genesis),
  },
}
```

If you just add a type here it should resolve the issue. To be clear, this isnt because you need to type this, it just needs to have statically analyzed `@formkit/vue`, but might as well add typings. FWIW — I don't think it should need this, so perhaps there is something we need to do in our Nuxt module to ensure our vue declarations are automatically included.

In the meantime this should "fix" it:

```ts
import { DefaultConfigOptions } from '@formkit/vue'
import { generateClasses } from '@formkit/themes'
import { genesisIcons } from '@formkit/icons'
import genesis from '@formkit/themes/tailwindcss/genesis'

const config: DefaultConfigOptions = {
  icons: {
    ...genesisIcons,
  },
  config: {
    classes: generateClasses(genesis),
  },
}

export default config
```

**Comment by Ragura** [comment]
This fixes both issues! Thank you for incredibly quick assistance!
